Section for feature/rework proposal design docs.
space-wizards/docs pull request #35
Opened 2023-09-26 18:28 UTC by TemporalOroboros

Adds a section between space-station-14 and the hosting guide for design proposals.

2023-09-26 22:37 UTC, mirrorcult commented
linkcheck is failing 
![image](https://github.com/space-wizards/docs/assets/19853115/1d167ff5-d6ba-444b-b164-48e7f86dd910)

2023-09-26 22:39 UTC, TemporalOroboros commented
Currently installing mdbook so I can see the problem.

2023-09-28 00:16 UTC, mirrorcult requested changes

2023-09-28 00:16 UTC, mirrorcult commented on src/en/general-development/tips/proposal-guidelines.md
> +``` admonish tip title="Design Principles"
```suggestion
``` admonish tip "Design Principles"
```

2023-09-28 00:16 UTC, mirrorcult commented on src/en/general-development/tips/proposal-guidelines.md
> +``` admonish warning title="Don't"
```suggestion
``` admonish warning "Don't"
```

2023-09-28 00:16 UTC, mirrorcult commented on src/en/general-development/tips/proposal-guidelines.md
> +``` admonish tip title="Unfinished Proposals"
```suggestion
``` admonish tip "Unfinished Proposals"
```

2023-09-28 00:17 UTC, mirrorcult approved these changes

2023-09-28 00:17 UTC, merged