Add atmos roadmap
space-wizards/docs pull request #78
Opened 2023-10-12 23:59 UTC by Partmedia

# Roadmap For Atmospherics

## Background

Most atmos players currently agree that atmos is not very fun to play, for some of the following reasons:

1. Most things like distro and the TEG are "set up and forget", which means that after setting up things at round start atmos techs think that they have nothing important to do. (In reality they should be monitoring for breaches and fixing them but whatever...)

2. Because of low transfer rates and slow spacing, atmos can't actually rectify problems in a reasonable amount of time. For example, if there actually is a plasma leak, scrubbers typically work too slowly resulting in the plasma inevitably being lit before it can be cleaned up.

3. Atmos techs entertain themselves by hyper-optimizing setups that produce tritium and frezon, neither of which are particularly enjoyable or engaing for the station to play with (see shuttle tritium bombing, mass frezon leaks). As a result, atmos is kind of detached from the rest of the station, basically playing their own game.

## Proposal

Make atmos more fun to play by:

1. Making the core job requirements more interesting and challenging. **An atmos tech's primary job is to keep the station livable and breathable.** There are a lot of interesting real life engineering problems to making this happen, including the fact that this is a station in space where every gas molecule wants to desperately escape into the cold of space. However, because of a few crutches like gas miners, heaters and freezers that beat thermodynamic limits, and magical devices that separate gases (filters and scrubbers) pretty much remove all of the challenging aspects of what would be a pretty incredible engineering feat.

2. Rewarding players for transfer of knowledge by increasing realism (see below note on realism before you immediately take issue). Making things behave in ways that you could reasonably expect from real life both caters to atmos nerds as well as makes behaviors more intuitive and discoverable. If players who play atmos discover through the game that they like chemistry in real life (and maybe even pursue a career in chemistry), then we should consider it a job well done.

### An Interlude on Realism

Upon hearing the word "realism," many folks turn out to have been professional game designers all their life and say something along the lines of:

> "This is a game, the point isn't to be realistic; the point is to be fun."

I agree with this sentiment completely. The point of a game is to be fun, not to be realistic (that is what simulators are for).

**However,** games are fun when players have a sense of agency (their actions matter in determining the final outcome of the game) and when their challenges are struggles are believable.

In order for players' challenges and struggles to be believable, the game universe must obey a consistent system of rules and physical limitations. It would not be fun if players have a way to *deux ex machina* out of every imaginable problem (e.g. Nukies? Why don't we use the magical remote control that makes all the nukies disappear? After all, we have *spess magic*.) We're in space, and it should be hard to get gases because they tend to escape into... you know... space. Not every station should have a magical gas miner.

But guess what? It turns out that realism provides both a set of interesting problems and a set of rules for how a universe should consistently behave. So by making things more realistic, we get both interesting mechanics and a set of consistent rules for free. Of course realism doesn't trump fun, and if it is fun to make something that is unrealistic (e.g. plasma gas), then we should always pick fun. **However, where realism does not conflict with being fun, then we should opt to be realistic because it provides a set of interesting problems and consistent rules.**

After all, why do we say that *PV=nRT*? Shouldn't we make up a different gas law because realism is bad?

## Concrete Proposals

In no particular order, specific mechanical changes that I think will accomplish goals 1 and 2 are:

- **Phase out gas miners for all upstream maps.** It doesn't make sense that all stations have free and plentiful sources of gas, otherwise you might as well be on a planet. This is a game that is literally set in space. It would make sense to keep a few specialty miners, e.g. for plasma, if a station is set on a plasma mining planet. But in general, all other gases should be imported via gas canisters. Miners should still be kept available for any forks that choose to use them.

- **Make all atmos devices flow-based.** This means driving gas flow as a result of pressure differences created using pumps. The specific offenders are currently any "pumped" device that is not a dedicated pump, e.g. air vents, scrubbers, filters, and mixers.

- **Make station air flow-based.** Currently, air vents release air when the pressure is too low, and by default scrubbers only scrub waste gases. So if for some reason the station gets cold, there's no easy way to cycle the air out and heat it up. Of course, you could set all the scrubbers to siphon, heat your distro, and then set the air alarm to fill. But that would just be describing a bad way of doing what real life HVAC systems have always been doing: keep the air flowing.

- **Make heaters and freezers thermodynamically sound.** Keeping a station properly heated or cooled is actually a substantial real-life problem. Why deprive atmos techs an actual challenge that keeps gameplay interesting? Because of the existence of generators like the TEG, keeping things thermodynamically balanced is also a great way to prevent infinite power hacks.

- **Make heaters and freezers binary.** Just like your central heating and air conditioning circulate air through heat/cold coils, gases should flow across heaters and freezers in order to exchange temperature.

- **Reworking scrubbers and gas filters.** One of the most pressing challenges in the real world is "how do you separate different kinds of gas." Most current methods of gas extraction are based on chemistry (e.g. real life carbon dioxide scrubbers contain chemicals that react with CO2, pulling it out) or physical methods (e.g. fractional distillation, where you cool down air in different stages to get liquid nitrogen, oxygen, etc.) This creates a lot of opportunity for new game play mechanics and industrial processes. This would also give more opportunities to add gas-based reactions (i.e. more content).

- **Add gas condensation.** This would enable fractional distillation and permit conversion between gas and the equivalent reagent.

- **Add pump efficiency curves.** Pumps have to work harder when they create a larger pressure difference. As a result, pumping from 1 atm to 2 atm should be easier (read: faster) than pumping from 1 atm to 10 atm. You could create a multi-stage pump, and indeed, that is what people in real life do, at the trade-off of less throughput.

- **Add maximum temperature and pressure limits for most devices.** It does not make sense that you can contain the surface of the sun in your pipes. Adding limits would encourage designing processes and systems that work within reasonable constraints.

- **Breaking windows at high enough tile pressure differences.** To handle explosions and resulting space wind without leaning on the explosino system, and to encourage people to design burn chambers with more controlled burns instead of always putting their pedal to the metal.

2023-10-13 00:17 UTC, mirrorcult commented
agree with pretty much all of this

2023-10-13 22:55 UTC, keronshb commented
> 3\. Atmos techs entertain themselves by hyper-optimizing setups that produce tritium and frezon, neither of which are particularly enjoyable or engaing for the station to play with (see shuttle tritium bombing, mass frezon leaks). As a result, atmos is kind of detached from the rest of the station, basically playing their own game.

This is part of being an atmos tech, almost a classic identity by being able to come up with wacky setups for fusion, gas making, etc. This should not be discouraged at all.


> ...then we should opt to be realistic because it provides a set of interesting problems and consistent rules.

I also do not agree with this. Realistic =/= interesting and peoples perspective on realism is a huge it depends (TM),
Making things into "realistic" just for the sake of realism isn't fun.

> 1. However, because of a few crutches like gas miners, **heaters and freezers that beat thermodynamic limits, and magical devices that separate gases (filters and scrubbers)** pretty much remove all of the challenging aspects of what would be a pretty incredible engineering feat.

You're asking to remove core gameplay mechanics of why people love to play atmos. Removal of these sounds like a HRP mechanic wishlist rather than an improvement.

> * **Phase out gas miners for all upstream maps.** It doesn't make sense that all stations have free and plentiful sources of gas, otherwise you might as well be on a planet. This is a game that is literally set in space. It would make sense to keep a few specialty miners, e.g. for plasma, if a station is set on a plasma mining planet. But in general, all other gases should be imported via gas canisters. Miners should still be kept available for any forks that choose to use them.

This sounds like a huge way to slow down gameplay "just because."

How would this be implemented? How would people feel rewarded by doing this over it being a chore and people not wanting to do this?

> * **Reworking scrubbers and gas filters.** One of the most pressing challenges in the real world is "how do you separate different kinds of gas." Most current methods of gas extraction are based on chemistry (e.g. real life carbon dioxide scrubbers contain chemicals that react with CO2, pulling it out) or physical methods (e.g. fractional distillation, where you cool down air in different stages to get liquid nitrogen, oxygen, etc.) This creates a lot of opportunity for new game play mechanics and industrial processes. This would also give more opportunities to add gas-based reactions (i.e. more content).

Don't turn atmos into a pseudo chemistry sim. I beg of you.
How does this also not have overlap with chemists?

2023-10-13 22:58 UTC, deltanedas commented
yeah this is good

also when miners are yoinked and the planet atmos bugs are fixed atmos could join salv on expeditions just to steal gases from the planet to save some money :trollface:

2023-10-13 22:59 UTC, Carolyn3114 commented
> Reference in

you could do this in lavaland but permanently

2023-10-13 23:00 UTC, deltanedas commented
actually yeah just have in and out fultons then do that forever

2023-10-13 23:07 UTC, Partmedia commented
> > 3. Atmos techs entertain themselves by hyper-optimizing setups that produce tritium and frezon, neither of which are particularly enjoyable or engaing for the station to play with (see shuttle tritium bombing, mass frezon leaks). As a result, atmos is kind of detached from the rest of the station, basically playing their own game.
> 
> This is part of being an atmos tech, almost a classic identity by being able to come up with wacky setups for fusion, gas making, etc. This should not be discouraged at all.

This design doc does not call for removing these. It calls for adding mechanics that create other problems and challenges.

> > ...then we should opt to be realistic because it provides a set of interesting problems and consistent rules.
> 
> I also do not agree with this. Realistic =/= interesting and peoples perspective on realism is a huge it depends (TM), Making things into "realistic" just for the sake of realism isn't fun.

These changes do not make things "'realistic' just for the sake of realism," it adds content by adding interesting problems to solve. Atmos techs can now hyper-optimize their oxygen setup in addition to hyper-optimizing other things.

> > 1. However, because of a few crutches like gas miners, **heaters and freezers that beat thermodynamic limits, and magical devices that separate gases (filters and scrubbers)** pretty much remove all of the challenging aspects of what would be a pretty incredible engineering feat.
> 
> You're asking to remove core gameplay mechanics of why people love to play atmos. Removal of these sounds like a HRP mechanic wishlist rather than an improvement.

Maybe to you.

> > * **Phase out gas miners for all upstream maps.** It doesn't make sense that all stations have free and plentiful sources of gas, otherwise you might as well be on a planet. This is a game that is literally set in space. It would make sense to keep a few specialty miners, e.g. for plasma, if a station is set on a plasma mining planet. But in general, all other gases should be imported via gas canisters. Miners should still be kept available for any forks that choose to use them.
> 
> This sounds like a huge way to slow down gameplay "just because."
> 
> How would this be implemented? How would people feel rewarded by doing this over it being a chore and people not wanting to do this?

See: https://github.com/space-wizards/space-station-14/issues/8311

There is also overwhelming consensus from [mappers](https://discord.com/channels/310555209753690112/770682801607278632/1162179968915210280) on this.

Overall I'm hearing "I don't like this" which is fine and a valid reason to not want something, but it would be helpful if you could write in with specific reasons and explanations so that we can come to a middle ground that everyone can agree with. Temperature checking the responses here it seems like most people are in favor of most of the items proposed.

2023-10-13 23:09 UTC, Carolyn3114 commented
I disagree with reworking filters and scrubbers like that, it would just complicate things way too much when there's no gas miners and atmos techs are trying to get co2 out of the station

2023-10-13 23:10 UTC, Carolyn3114 commented
and to deal with no gas miners, it would have to be like ss13 where the gas chambers start with thousands of mols, and there's computers to limit the output and check it

2023-10-13 23:11 UTC, Partmedia commented
> I disagree with reworking filters and scrubbers like that, it would just complicate things way too much when there's no gas miners and atmos techs are trying to get co2 out of the station

I appreciate your input.

These changes won't all land in at once. Most likely miners will be removed, and then we'll play the "we'll see" game and see if the filters and scrubbers need to be adjusted. Certainly, they will not be removed without a reasonable alternative being available.

> and to deal with no gas miners, it would have to be like ss13 where the gas chambers start with thousands of mols, and there's computers to limit the output and check it

Right. And cargo techs can still order in more gas.

2023-10-13 23:18 UTC, Carolyn3114 commented
and I think for pipes and canisters being able to hold infinite pressure and temperature, they could give off heat, explode, and leak when taking damage / when too hot, but you should be able to upgrade them with plasteel 
*OR* be able to enable a "shield mode", which makes them exponentially use power depending on how much damage they would be taking

2023-10-13 23:19 UTC, Carolyn3114 commented
so if you have a canister or pipeline with the pressure and heat of the sun, it'd take a megawatt of power to keep the shield going, or else it'd explode

2023-10-13 23:21 UTC, Partmedia commented
> and I think for pipes and canisters being able to hold infinite pressure and temperature, they could give off heat, explode, and leak when taking damage / when too hot, but you should be able to upgrade them with plasteel

I think that would be cool, and having upgraded plasteel pipes was proposed in the other PR.

> so if you have a canister or pipeline with the pressure and heat of the sun, it'd take a megawatt of power to keep the shield going, or else it'd explode

Something like the fusion engine actively containing the fusion. This was proposed in https://github.com/space-wizards/space-station-14/pull/19103.

2023-10-13 23:23 UTC, Carolyn3114 commented
> > and I think for pipes and canisters being able to hold infinite pressure and temperature, they could give off heat, explode, and leak when taking damage / when too hot, but you should be able to upgrade them with plasteel
> 
> I think that would be cool, and having upgraded plasteel pipes was proposed in the other PR.
> 
> > so if you have a canister or pipeline with the pressure and heat of the sun, it'd take a megawatt of power to keep the shield going, or else it'd explode
> 
> Something like the fusion engine actively containing the fusion. This was proposed in [space-wizards/space-station-14#19103](https://github.com/space-wizards/space-station-14/pull/19103).
fusion wouldn't be the only thing that would require high heat, stuff like crystallization would suck without a way to stop them exploding, but yeah, adding the HFR from ss13 would be cool

2023-10-13 23:25 UTC, keronshb commented
> This design doc does not call for removing these. It calls for adding mechanics that create other problems and challenges.

You're removing the core way of doing it + adding pipe damage.

> These changes do not make things "'realistic' just for the sake of realism," it adds content by adding interesting problems to solve. Atmos techs can now hyper-optimize their oxygen setup in addition to hyper-optimizing other things.

Please explain how this would be done. To me it sounds like you're just proposing a system that's more difficult just because, rather than build off of the atmos system that people love to work with for over a decade.

> Maybe to you.

Literally any atmos main from the past decade would look at these changes with huge scrutiny.
That's not saying change can't happen. Just the way you're proposing it make an already difficult system more difficult for "realism"

> See: [space-wizards/space-station-14#8311](https://github.com/space-wizards/space-station-14/issues/8311)

I see "put things behind cargo and mining" which has been a huge issue in the past.

> Overall I'm hearing "I don't like this" which is fine and a valid reason to not want something, but it would be helpful if you could write in with specific reasons and explanations so that we can come to a middle ground that everyone can agree with. Temperature checking the responses here it seems like most people are in favor of most of the items proposed.

Please do not reduce my comments down to "I don't like this."

Part of it is I do not like it, yes. But a huge chunk of it comes from literal decades of SS13 play and how it was changed, how I've seen players interact to changes to established systems, and why the realism argument hasn't been good for servers unless it was a HRP server.

HRP servers are commonly agreed upon to be the servers that would be the most hyper realistic. Things become more of a chore because HRP players like it that way.

LRP-MRP players do not like these kinds of changes, especially making difficult systems more difficult. It bogs down gameplay and if something is too big of a chore, players will not want to do it.

"this game isn't ss13"
Yes but this game is also based on SS13 and whenever BYOND dies, it's one of the main games to come to.

2023-10-13 23:27 UTC, Carolyn3114 commented
when fires and stuff work completely, it'd be nice to get 

> so if you have a canister or pipeline with the pressure and heat of the sun, it'd take a megawatt of power to keep the shield going, or else it'd explode

this would also help against plasma fires, because if you tried to siphon out the superheated gas, it would cause all of the scrubber line to instantly break, basically killing everyone on station from overpressurization and heat

2023-10-13 23:28 UTC, Carolyn3114 commented
also scrubbers kinda suck at siphoning right now anyway, so most of the time people just space rooms if it's too much of a hastle

2023-10-13 23:32 UTC, deltanedas commented
> Literally any atmos main from the past decade would look at these changes with huge scrutiny.

i play atmos a good bit and i dont mind the changes

@Ilya246 @BasedUser

2023-10-13 23:33 UTC, mirrorcult commented
> Literally any atmos main from the past decade would look at these changes with huge scrutiny.

hi

2023-10-13 23:57 UTC, keronshb commented
> > Literally any atmos main from the past decade would look at these changes with huge scrutiny.
> 
> hi

What do you like about it exactly? There's a lot of huge QOL loss if scrubbers, vents, etc get removed and the ceiling /learning curve gets raised a LOT.

2023-10-14 00:18 UTC, Partmedia commented
> What do you like about it exactly? There's a lot of huge QOL loss if scrubbers, vents, etc get removed and the ceiling /learning curve gets raised a LOT.

I'm not suggesting that scrubbers and vents get removed overnight without replacement. What I'm advocating for is are mechanics where it takes a little more work to separate gases, be it by cooling it down and fractionally distilling it, or separate machines in atmos where you have to send all the waste gases to in order to be processed. Maybe scrubbers and vents stay as a higher-tier research technology.

A LOT of people bring up "accessibility" or "learning curve" issues, but:

- Atmos already has a high learning curve. Frezon production is not documented anywhere. Tritium supersaturation is not documented anywhere. Yet these features were still added.
- I argue that increasing realism *reduces* the learning curve because intuition from real life transfers over to the game and vice versa. There's a reason we use $PV=nRT$ instead of some other random made-up formula.
- Even if there was a learning curve, there are ways to reduce it. For example, one could argue that the TEG is unintuitive and has a high learning curve. But that's offset by the round-start TEG layout existing. Depending on the layout, you could literally flip a few valves and be on your way.
- The opposite of having a learning curve is not having anything to learn. If you instantly master it, what game is there left to play?
- Of course I would advocate for documentation/guidebook entries that explain new mechanics as they are developed.

2023-10-14 00:42 UTC, keronshb commented
> I'm not suggesting that scrubbers and vents get removed overnight without replacement. What I'm advocating for is are mechanics where it takes a little more work to separate gases, be it by cooling it down and fractionally distilling it, or separate machines in atmos where you have to send all the waste gases to in order to be processed. Maybe scrubbers and vents stay as a higher-tier research technology.

Locking QOL behind research is also not a good gameplay mechanic. There's a core issue of relying too much on cargo, mining, and science. This sounds like it will add to the problem.

> Atmos already has a high learning curve. Frezon production is not documented anywhere. Tritium supersaturation is not documented anywhere. Yet these features were still added.

Documentation issue? I don't know how this is relevant.

> I argue that increasing realism _reduces_ the learning curve because intuition from real life transfers over to the game and vice versa. There's a reason we use

I feel like this should be part of a different game?

Yes SS13 started as an atmos sim, but it's grown much much more since that.

SS14 doesn't exist to train people to learn about real life atmos. That seems better suited for an actual pure 100% atmos sim game.

> Even if there was a learning curve, there are ways to reduce it. For example, one could argue that the TEG is unintuitive and has a high learning curve. But that's offset by the round-start TEG layout existing. Depending on the layout, you could literally flip a few valves and be on your way.

TEG is a boring engine either way and it should not become the standard. Do not just focus on the TEG as there are other engines (Turbine, Solars, The Super Matter Crystal, Tesla, Singulo, AME, etc). Some of which aren't in yet.

I've seen some INSANE setups on the SM with the current system in play. There's an infinite number of ways to optimize the SM and run it with different kinds of gasses with the SS13 system.

> The opposite of having a learning curve is not having anything to learn. If you instantly master it, what game is there left to play?

Disingenuous argument. That's assuming there's an instant way to mastery here which there isn't.

The current vent/scrubber system right now is a huge QOL. If you remove that QOL all it does is bog the game down and people are less likely to want to play Atmos or learn it.

Now, adjusting scrubbers to require filters/mixers is more of an interesting gameplay.

For example. There's no reason to use filters over scrubbers for bomb making unless you're working on some high level atmos project.

Now if scrubbers had limited filters (instead of catch all), it could encourage the use of using the filters or mixers. Or something similar by being able to adjust scrubbers to be more optimized for the situation.

How would this new atmos system encourage fire-fighting if scrubbers, etc are gone?
How would it discourage spacing tiles if it's too hard to learn?
How would this system work with the super matter crystal if it's implemented before this?

Instead of introducing progression on a system that works, it feels like it's taking a huge step back and not looking at what makes the current system work well and improving upon that.

Gas miners - you could take a factorio approach by allowing them to be placed on a planet and then bluespaced back up to the station, but then would you give Engineering/Atmos Techs mining/planet access or would this be another issue of locking content behind cargo/mining/science?

2023-10-14 02:24 UTC, mirrorcult approved these changes

2023-10-14 02:47 UTC, moonheart08 requested changes
A lot of this seems like it'll ***dramatically*** increase the barrier of entry to atmospherics to absolutely unacceptable levels, and I'm blocking this document until you have extremely concrete plans on how to make this stuff intuitive without telling players to solve equation systems to play the game.

2023-10-14 03:06 UTC, moonheart08 commented
> > What do you like about it exactly? There's a lot of huge QOL loss if scrubbers, vents, etc get removed and the ceiling /learning curve gets raised a LOT.
> 
> I'm not suggesting that scrubbers and vents get removed overnight without replacement. What I'm advocating for is are mechanics where it takes a little more work to separate gases, be it by cooling it down and fractionally distilling it, or separate machines in atmos where you have to send all the waste gases to in order to be processed. Maybe scrubbers and vents stay as a higher-tier research technology.
> 
> A LOT of people bring up "accessibility" or "learning curve" issues, but:
> 
>     * Atmos already has a high learning curve. Frezon production is not documented anywhere. Tritium supersaturation is not documented anywhere. Yet these features were still added.
Okay. Axe it. Seriously, go ahead, axe it, I'll watch. Either you work toward making atmospherics a mechanic that can be engaged with without needing to grab a graphing calculator. Either that, or properly document the broad strokes of how these mechanics work, in general terms, **without requiring anything more than algebra.**
Existing design issues do not justify adding more design issues.

> 
>     * I argue that increasing realism _reduces_ the learning curve because intuition from real life transfers over to the game and vice versa. There's a reason we use PV=nRT instead of some other random made-up formula.
This is only true to a point. Like every design process, there is a balance here and the balance here is "what does a player expect from their everyday experiences". PV=nRT, as abstract as it is, still models concepts that are intuitive to players, and this is why it works. A player expects gas to fill a volume, expects it to move to fill larger volumes, expects it's pressure to adjust to the size of it's volume based on quantity, and expects pressure to go up/down as it gets hotter or colder. These are all things one can infer from the every-day and a bit of high school.
On the flipside, and an extreme example, fractional distillation is also a real world process but is absolutely not intuitive due to how temperature, pressure, gas/liquid phase transition, etc behave in a real world process. A system like that absolutely needs heavily abstracted, the real world equations should **not** be used, and I want to see concrete information on how you can map mechanics you intend to implement to real world intuition.

Reality is not intuitive because it's reality, it's intuitive because we interact with it a lot, and the parts of reality we rarely see are anything but intuitive.
> 
>     * Even if there was a learning curve, there are ways to reduce it. For example, one could argue that the TEG is unintuitive and has a high learning curve. But that's offset by the round-start TEG layout existing. Depending on the layout, you could literally flip a few valves and be on your way.
> 
>     * The opposite of having a learning curve is not having anything to learn. If you instantly master it, what game is there left to play?
As Keron said, this is just disingenuous. Not humoring this, have a funny comic as response.
![R](https://github.com/space-wizards/docs/assets/7806367/80e927f4-2d73-44b2-babb-63e8d64608eb)
Nobody is arguing for the opposite, we are arguing for having a low skill floor. Complex mechanics should be introduced gradually, and build atop one another. Ideally, mechanics themselves are individually simple, light on math/experience requirements, etc, and it's the **combination of those mechanics** that should build into your complex system. Addition of out of the gate complexity should be done carefully and not just for the sole purpose of realism. For example, I see no mechanical gain to pump efficiency curves beyond what we already have, there's no gain for the player and it's sole reason seems to be "realism", when in this case the realism is less intuitive to the player, as they don't anticipate pumps curving like that unless explicitly told.

A great rule when designing game mechanics is that one should minimize the amount that needs explained about the trivialities. A pump is a pump, a core building block, and should be as simple as feasible due to this, but the things one can then *do* with that pump can be complex. Having to pull out a graphing calculator to judge what layout of pumps I need to achieve the desired tradeoff is not ideal unless opt-in. In fact this is already done, with the distinction between volumetric and pressure pumps, and *their* tradeoffs. We already have a tradeoffs game integrated that's much simpler to explain to a player (precise throughput control or precise pressure control, your pick, no wonky graph to figure out.)
> 
>     * Of course I would advocate for documentation/guidebook entries that explain new mechanics as they are developed.



All in all: this is a **game**, people **play** it, please remember that. The industrial design simulation game is not built here, spaceman game with giant fires, explosives, traitors, and clowns is.

2023-10-14 04:12 UTC, Partmedia commented
Thank you for writing in with your concerns. Hearing from everyone gives us the best game possible.

> > * Atmos already has a high learning curve. Frezon production is not documented anywhere. Tritium supersaturation is not documented anywhere. Yet these features were still added.
> > ```
> 
> Okay. Axe it. Seriously, go ahead, axe it, I'll watch. Either you work toward making atmospherics a mechanic that can be engaged with without needing to grab a graphing calculator. Either that, or properly document the broad strokes of how these mechanics work, in general terms, **without requiring anything more than algebra.** Existing design issues do not justify adding more design issues.

I don't want to axe it. Making tritium and frezon is fun. I said this in response to the argument that "the learning curve is too high, therefore this feature shouldn't exist" and pointed out existing features that do exist that have high learning curves and poor documentation.

I do not plan to require algebra. I do not plan to require math. All of the design mechanisms that I proposed are based on these fundamental, intuitive ideas:

1. You should not be able to spin energy out of thin air.
2. You should not be able to spin matter out of thin air.
3. When given a choice, gas flows from high pressure to low pressure.
4. When given a choice, temperature transfers from hot to cold.
5. A higher pressure difference should be harder to overcome than a lower one.
6. Players should be able to meaningfully impact game play.

> This is only true to a point. Like every design process, there is a balance here and the balance here is "what does a player expect from their everyday experiences". PV=nRT, as abstract as it is, still models concepts that are intuitive to players, and this is why it works. A player expects gas to fill a volume, expects it to move to fill larger volumes, expects it's pressure to adjust to the size of it's volume based on quantity, and expects pressure to go up/down as it gets hotter or colder. These are all things one can infer from the every-day and a bit of high school. On the flipside, and an extreme example, fractional distillation is also a real world process but is absolutely not intuitive due to how temperature, pressure, gas/liquid phase transition, etc behave in a real world process. A system like that absolutely needs heavily abstracted, the real world equations should **not** be used, and I want to see concrete information on how you can map mechanics you intend to implement to real world intuition.

I understand your concern. I'll respond by saying:

1. I'm not an industrial or mechanical engineer. I'm learning fluid flow for the first time along with everyone else. When I look up a formula it's to get a rough feel for how things are supposed to behave in real life (e.g. $T^4$ for radiation). When things are too complicated to be fun, I simplify. In the radiator code you'll see an $alpha$ that abstracts away a lot of the real equation. This isn't my bread and butter, I'm making reasonable trade offs for fun, too.
2. Fractional distillation is a fancy way to say "when you cool a gas it turns into water" and "when you heat a water it turns to gas". Different gases have different threshold temperatures. My specific idea here is to implement gas condensation/evaporation with the constants that are *already in the YAML files* so that players can separate gases from one another by evaporating a mixture at a certain temperature, collect the gas, then change the temperature, then collect a different gas. You'll notice that no math is involved, beyond "is one number bigger than the threshold".

It's a lot of work to fully specify each of the mechanisms that I propose, so if you have specific concerns about a specific mechanic, give me the number and I'll make a short writeup about it.

> Reality is not intuitive because it's reality, it's intuitive because we interact with it a lot, and the parts of reality we rarely see are anything but intuitive.

I'm hoping that we can get good content out of the interesting bits without it being too overwhelming. I'm glad I have you here to tell me if and when it does.

> Nobody is arguing for the opposite, we are arguing for having a low skill floor. Complex mechanics should be introduced gradually, and build atop one another. Ideally, mechanics themselves are individually simple, light on math/experience requirements, etc, and it's the **combination of those mechanics** that should build into your complex system.

That's what I'm proposing. I'm not going to overhaul all of atmos overnight. These are examples of the high level ideas that I'm proposing, feature by feature, bit by bit. None of them will shake up atmos overnight. All of the features will be balanced with existing features in mind. Not all of these features will be implemented. If there is strong objection to any particular proposal, we can axe them.

> Addition of out of the gate complexity should be done carefully and not just for the sole purpose of realism. For example, I see no mechanical gain to pump efficiency curves beyond what we already have, there's no gain for the player and it's sole reason seems to be "realism", when in this case the realism is less intuitive to the player, as they don't anticipate pumps curving like that unless explicitly told.

The specific reason is that trade-offs are good (an argument that you've explained to me before).

The trade-off with pump efficiency curves is that you either can make 1) a pump that moves a lot of moles very quickly but across a low pressure differential or 2) you can have a pump that moves a few moles very slowly but across a huge pressure differential.

This makes intuitive sense because it's more work to walk up a steep hill compared to a shallow hill.

It also allows for in-game trade-offs. And trade-offs are good, right?

> A great rule when designing game mechanics is that one should minimize the amount that needs explained about the trivialities. A pump is a pump, a core building block, and should be as simple as feasible due to this, but the things one can then _do_ with that pump can be complex. Having to pull out a graphing calculator to judge what layout of pumps I need to achieve the desired tradeoff is not ideal unless opt-in. In fact this is already done, with the distinction between volumetric and pressure pumps, and _their_ tradeoffs. We already have a tradeoffs game integrated that's much simpler to explain to a player (precise throughput control or precise pressure control, your pick, no wonky graph to figure out.)

I agree that there should be no need to pull out a graphing calculator. None of these mechanics are designed to require a graphing calculator to play.

(Although, the current game mechanics fail miserably at this, because there is a maxcap calculator floating out there.)

> > ```
> > * Of course I would advocate for documentation/guidebook entries that explain new mechanics as they are developed.
> > ```
> 
> All in all: this is a **game**, people **play** it, please remember that. The industrial design simulation game is not built here, spaceman game with giant fires, explosives, traitors, and clowns is.

I agree. I play this game too. We're here to have fun. But as most people will currently agree, there is a lack in specific job content. I'm hoping that I can at least make atmos a bit more fun to play.

2023-10-14 05:15 UTC, BasedUser commented
since i was pinged, might as well say this

2022 atmos was fine and nobody bat an eye until people started optimizing tritium/frezon - now we have atmos players
2023 atmos was fine before radiators broke all balance by radiating into /dev/null, and then freezers were also realified for some reason instead of radiators being fixed ("just use ss13 values" doesn't work on maintainers apparently) - i'm pretty sure if radiators were fixed to start with (and slightly stronger, i.e. what Partmedia:notafet/passiveradiator wants to do) and the freezer realism update never happened not a single atmos would be mad

there's two ways atmos goes, either with reverts and more careful ports of atmos devices from goon/tg; or with a complete rework of piping as it currently exists and a new atmos balance (this isn't ammo techfabs on cargo anymore)

i'm all for new balance if it makes fixing breaches or cooperating with, vox, plasmemes (which don't exist), or any departments that actually could use atmos content (medical with MRIs and smartfridges? sec with superconducting coilguns? service with nitrobrew coffee?) any more fun, but my only gripe is if you're making something based on reality, make it happen in more time-compressed/time-dilated frames - i.e. freezers, radiators, fusion reactions, the SM

overall i agree with this but as it currently exists there's a triangle of fun, realistic and balanced out of which you can only choose two things
a rework would need to do all three

2023-10-14 05:24 UTC, Ilya246 commented
as for my input,
* gas miners:
i think gas miners should not be removed and should instead just produce a very low (like 4 mol/s? ~25s to refill a tile) amount of gas, to prevent the air supply from just completely dying if cargo dies
* filters:
i am very much against making filtering harder, due to complexity concerns if this is introduced i don't think anyone will play atmos anymore (see: TEG, it's easy yet people can't do it)
as an alternative, i would suggest making filters take power and scrubbers take even more power
* making the game thermodynamically sound:
again, as others mentioned, i think this goes *against* fun: non-thermodynamically-sound atmos is just more fun to play with; with thermodynamic atmos you can't do nearly as much as otherwise (big number funny), which is not fun
* additionally, on device stacking:
i think device stacking should be allowed, but only if the devices are rotated differently, aka the same way the no-pipe-stacking PR works: if you try to build a device that would have one of its pipes overlap with an already existing pipe on this tile, don't allow you to

2023-10-14 05:31 UTC, Carolyn3114 commented
I'd love if atmos worked like how it did in ss13, but that'd require removal of miners

2023-10-14 05:50 UTC, keronshb commented
> i think device stacking should be allowed, but only if the devices are rotated differently, aka the same way the no-pipe-stacking PR works: if you try to build a device that would have one of its pipes overlap with an already existing pipe on this tile, don't allow you to

This is what layered devices/piping could work for.

2023-10-14 09:31 UTC, Ilya246 commented
>     1. Rounds are ~1 hour long.
> 
>     2. Spending most of that time on maintaining the status quo just so the round doesn't end is not fun nor desirable
> 
>     3. Fire-and-forget machines allow for players to interact with other players, without being forced to babysit numbers.
> 
>     4. Automation is good, tedious maintenance is not.
> 
>     5. Realism doesn't matter, cohesion does matter.
> 
>     6. Flow is not fun to work with, mainly due to time demands.
> 
>     7. Repairing and maintenance could be a separate role for people that enjoy tedious and monotonous tasks, like janitor.
> 
>     8. Atmospheric Technician could be a science-like role that exists to push new technology in form of player-driven research in atmos designs. For comparison, science is predetermined research where players only press buttons to unlock it, atmos is limited by actual player ability and knowledge.
> 
>     9. Hyper optimized frezon builds are fun, managing 101kpa 20C gas is not fun.

i agree, yes
flow-based devices are bad and radiators should act like a straight pipe or just be unary

2023-10-14 17:15 UTC, Partmedia commented
How do we want to move forward with this? I've been hearing a lot of "this is good" and "this is bad" and everyone has a different opinion. It doesn't sound like we're going to get consensus. I've responded to some specifics but it doesn't sound like people want to change their minds. Discussion has now devolved into something like:

> i agree, yes

i disagree, no

> flow-based devices are bad and unintuitive (i don't think i have seen a single person that gets how radiators work yet) and radiators should act like a straight pipe or just be unary

flow-based devices are good and intuitive (i think i have seen many people understand how radiators work) and  radiators should act like a binary device

And personal attacks:

> If your radiators are any indication, it's absolutely horrendous to make them function and not fun at all.

2023-10-14 17:50 UTC, keronshb commented
> How do we want to move forward with this? I've been hearing a lot of "this is good" and "this is bad" and everyone has a different opinion. It doesn't sound like we're going to get consensus. I've responded to some specifics but it doesn't sound like people want to change their minds. Discussion has now devolved into something like:

This isn't a change my view thread. This is a discussion.

While it does feel some comments can be heated, please be more than aware that your opening comments can be taken as a bit hostile and anti-criticism such as:

> 2\. (see below note on realism before you immediately take issue).

> Upon hearing the word "realism," many folks turn out to have been professional game designers all their life and say something along the lines of:

> **However, where realism does not conflict with being fun, then we should opt to be realistic because it provides a set of interesting problems and consistent rules.**
> 
> After all, why do we say that _PV=nRT_? Shouldn't we make up a different gas law because realism is bad?

Despite what your intentions may have been, these comments in the opening message come off as "I do not want to take criticism and here are my sentences to hand wave it." and it does feel like that's the way you've been handling criticism on this.

But I'm not here to discuss that.

Clearly there's an issue here with how this roadmap is written and how it can be discerned.

To me, it doesn't feel like enough proper research was done on how a typical LRP/MRP SS14 round plays out or what the current system is based off of. It just comes off as "the roadmap ideas are a cool concept for an atmos sim"

WHICH! Ok! Some of these deas can absolutely rock on a HRP server.

NRP/LRP/MRP server rounds typically last for 1hr. Depending on the round they may last 30 minutes, or they could last two hours. Very ambitious servers may have rounds extend up to 3-4 hours as an upper limit.

HRP servers are mileage may vary but some HRP servers don't have "rounds" and just have one continuous round, which is what most of these designs in here seem way more fit for.

It doesn't feel like most of these planned ideas would work with your typical SS14 round.

Please also realize we don't have absolutely all of the devices & pipes in yet from SS13. We're currently missing:

- Rapid Pipe Device (to make setups & repair pipes)
- Heat Exchange Pipes
- Heat Exchangers
- Pressure Release Valves

There are probably more but those come to mind after doing a comparison last night.

There's also conflicting ideas:

> 1. Most things like distro and the TEG are **"set up and forget"**, which means that after setting up things at round start atmos techs think that they have nothing important to do. (In reality they should be monitoring for breaches and fixing them but whatever...)

conflicts with this:

> 3\. As a result, atmos is kind of detached from the rest of the station, basically playing their own game.

It doesn't say how this new system would help prevent "atmos playing their own game".

Locking gasses behind Cargo & Mining (Department) does not == "interacting with others" or "not playing their own game"

Having pipes blow up at high pressure also does not solve this either, but instead makes dealing with fires, and potential catastrophic SM engine failures, EXTREMELY more annoying.

> 2\. Rewarding players for transfer of knowledge by increasing realism

This doesn't make atmos more fun to play. I highly doubt most people playing atmos are going to go on to be a real life atmos tech or even realize half of these things.

Now this isn't every thing I can go over but when I have more time I can.

I'm also going to throw my hat into the ring and say this requires more thought before being able to act on it.

Please also learn to take criticism.

2023-10-14 17:51 UTC, keronshb submitted a review, later dismissed
Also requesting changes

2023-10-19 22:54 UTC, Jezithyr commented
I think the best solution to atmos is somewhere in the middle ground. Introducing elements of chemistry to atmospherics is a good idea that helps bring inter-department cooperation and generally gets atmos techs to actually move around the station. One issue I have with this proposal is that if focuses too much on the realism aspect and not enough on the actual implementation. 

For example getting rid of gas miners is a great idea, [I have an atmospherics design doc that outlines a similar idea](https://lucid.app/lucidspark/3020d3e7-91d6-4928-b03f-96daa4d476e9/edit?viewport_loc=-16987%2C-2525%2C24000%2C11588%2C0_0&invitationId=inv_6d09f250-1226-4cc3-8b90-4fbac86049e2). Purely relying on cargo/gas imports is a risk since cargo is not always staffed. A solution to that issue would be to have randomly generated asteroids that have gas geysers on them. These geysers can be unlimited for certain gasses or limited for rarer gases. This encourages atmos to work with cargo/salvage or go eva to setup extractors if no salvage players are available. Gas recycling and heat management are definately fun mechanics that i think could add alot of nuance to atmos. Gas recycling also has possible overlap with botany since plants could be bred to filter or release specific gases.

One of the issues I have with most engines in SS13 is like you put it, their setup and forget nature. A possible solution for this is maintenance and degradation. This is something that can very easily kill atmospherics as a job if done poorly, but if done well it can encourage engineers to migrate through the station and intermingle with other departments. This can also have tech tree integration for technologies that offer more efficent versions of machines or decrease maintenance. (This also gives a job for maint borgs).

For generators/engines I think it's important to remember that powerplants irl are designed to have the minimal amount of human involvement. This is boring for a videogame. On one extreme you have wacky supermatter engines that have fancy gas mixtures and need constant supervision, while on the other you can hellburn TEGs that are just set and forget. Personally I think the solution is somewhere in the middle and integrates research and the tech tree. Designing our engines to require minor setup but regular upkeep is a good way to remove "checklist" gameplay from atmospherics. Because let's be real, after the 10th time of setting up the supermatter it gets old. Tying engine progression to reserach means that engineers are incentivized to actually upgrade the engine for better efficency and maintenance.

2023-10-19 22:55 UTC, Jezithyr approved these changes
Clicked the wrong button

2023-10-19 22:55 UTC, Jezithyr requested changes
Also requesting changes, see my above comment. we should discuss this more on discord and figure out concrete design concepts for how to go about making atmos better

2023-10-20 01:26 UTC, keronshb commented
Imagedump time.

![Atmos Box SS13](https://github.com/space-wizards/docs/assets/54602815/1a0c1d00-e694-4ea9-b673-3b0a2682035f)

This is a portion of Box's Atmos on Citadel. A lot going on here but the blue pipe is the atmos mix. Offscreen is a heater that heats the gas up. All the gas mined here are cooled.

![layer adapter](https://github.com/space-wizards/docs/assets/54602815/0f4d9ee1-4d52-4779-9991-c87384776fbf)

Example of a layer adapter in front of one of the miners.

![PumpO2](https://github.com/space-wizards/docs/assets/54602815/891e6e42-ffa0-4faf-bbf8-86491e606d0d)

An example of how simplicity can add to fun. Hooking up a pump and an o2 tank to two faced connectors to supply a refillable air to the station.

![RPDMenu](https://github.com/space-wizards/docs/assets/54602815/cc629542-63d0-4ade-a92e-c25df4d1455c)

RPD menu

![Layer321](https://github.com/space-wizards/docs/assets/54602815/2799db9f-b0c2-425e-99bc-ce0c81716dc7)

Basic pipe layers. In order: 3 2 1. Color coded them for ease of access.

![LayersMorePipes](https://github.com/space-wizards/docs/assets/54602815/12c104c3-56f8-47da-817f-a8702b9c0352)

What some simple pipes look like attached

![LayeredPipeExamples](https://github.com/space-wizards/docs/assets/54602815/6b8c5642-a15e-4050-af48-c205c731b720)

This is just nonsense I made but here's a bunch of pipes & devices that could work in tandem with each other with layered (and regular) pipes.

2023-10-20 04:56 UTC, Partmedia commented
Updated proposal based on feedback from many:tm:.

2023-10-20 13:16 UTC, keronshb commented
Your links are broken and link to creating a pull request.

2023-10-20 13:28 UTC, keronshb commented
I'm going to do this in chunks. The design principal link that works: https://docs.spacestation14.com/en/general-development/feature-proposals/ss14-fundamental-design-principles.html

> 3\. Atmos techs don't play with the rest of the station, preferring to isolate themselves to produce a funny green gas that is only particularly useful for shuttle bombing. Mechanics like this violate the [fundamental design principles](en/general-development/feature-proposals/ss14-fundamental-design-principles.md). While these mechanics shouldn't be removed per-se, more focus should be given to mechanics that increase interactions with the station, like making sure the air is breathable and well-heated.

You're hyper focusing on the wording used in the documentation.

Solo play =/= viloating fundamental design principals.

> Mechanics **should seek to be pro-social and encourage interacting** with other players. These **interactions need not be strictly cooperative or competitive in nature.** Humans are chaotic by nature, and provide depth and replayability to games that cannot fully be achieved through programmed mechanics alone. Thus, we should utilize that power to drive gameplay. Mechanics which incentivize players to do them entirely alone, or mechanics which would be just as fun and fulfilling if done on a private test server with only one player, will not be added to SS14.

I cannot stress this enough. Having some solo gameplay elements does NOT mean it's violating anything said here.

You can have both social gameplay elements AND solo gameplay elements.

There's a huge pitfall with hyper focusing on social elements - dependencies on others vs self.
There will be scenerios where gameplay will warrant social interaction.
There will also be scenerios where gameplay will warrent "solo play"

Making setups in atmos or in the engine is not violating that doc at all.

Conversely, setup and forget engines aren't also terrible either.

Do we want engines that require more interaction than setup? For sure. (The SM can 100% provide this)
But do we want engineers to babysit the engine most of the shift? NO.

So one huge word of warning from me is to please do not hyper focus on "single player vs multi player" when looking at some atmos mechanics.

2023-10-20 19:30 UTC, Ilya246 commented
we had some discussion over on discord, and i think:
- flow-based devices are okay
they might be a little bit harder to use than current devices, but they provide much better interoperability with changes to pumps
should work fine if atmosians teach each other to put pumps before devices
- pressure softcap + efficiency curves are good
as in:
1) making pumps pump slower from low to high pressure and faster from high to low pressure
2) removing all hard pressure limits, instead relying on pipe burst limits
3) differentiating pumps to throughput-centric (volumetric gas pump) and pressure-centric (gas pump)
this will still allow you to do most of what old atmos could do while not being easy to understand (high pressure = slow pump), again provided atmosians teach each other
- device differentiation is good
keep thermodynamically "magic" devices as they are, but have thermodynamically sound variants (radiators, heat pumps) for "industrial" temperature control options
make sure thermodynamically sound options are *much* stronger but require setting up
- overall:
i think the proposal is overall good (it's being edited at the time of writing of this comment, referring to the future version) and will allow for more intuitive atmos where you can get by in a lot of places with "high pressure likes to go to low pressure and doesn't like going back" and not change the type of atmos gameplay too much, besides increasing interdepartmental cooperation by phasing out gas miners

2023-10-20 19:57 UTC, evilexecutive commented
I have my own gameplay expansion pitch for Atmospherics, and that centers around purchasing and exporting gas. What if Atmos had a docking arm for their section, with pumps made to line up and attach to those of incoming ships. Say if the station air tanks are running low on nitrogen, Atmos would order a nitrogen tanker ship be sent to the station. They then have to drive the tanker to the atmos docking arm, then go spacewalk to connect it up. And once they're done pumping air out of the tanker, the atmos techs would then have to send the tanker back. Or they could pump manufactured gasses into the tanker, which can be sold for profit. 

This kind of system could actually entirely replace the need for miners on maps.

2023-10-21 05:21 UTC, ViceEmargo commented
Here are a few of my thoughts as a new player and atmos tech.
I came into Atmos thinking pressure unanimously determined flow.
Heaters and Freezers are strange, but understandably simple for now, I entertain the thought that there should be tiers of these devices that determine what temperatures and pressures they can perform. Although, I think they should DISPLACE heat, and not just delete or create heat.
The gas miners are a weird but understandably free source of gas resources. I think instead of having a gas miner for each gas, have a large industrial machine gas miner which creates all of the gases and must be supplied with a lot of power. (Do the current gas miners consume power?)
At the start of a shift, atmos can set up gas tanks that they tend to start with while they setup the industrial miner with filters.
Right now, Atmos is **"set and forget"** and sometimes not even that. You can do the bulk of your necessary tasks in the first 5 minutes of a shift and hang out in the bar until the station gets spaced or events happen.
I was surprised to experience that oxygen does not have the capacity to ignite on it's own but requires plasma.
Perhaps it will be too much of a headache, but I would love to see state changes for every material based on pressure and temperature.
Having liquid and solid forms of gases would be neat.

I like much of the statements made in this post, although I can't pretend to know anything about real life thermodynamics or gas laws to back the proposal of making the game lean more towards gas simulation.

2023-10-22 00:14 UTC, keronshb commented
OK SO. My whole point here is to not reinvent the wheel if we don't need to + avoid the gameplay mistakes of the past.

I've reread the new proposal (again) and while I do agree with most changes there are still some issues I'd like addressed. Some of this will be repeats from what we talked about on discord.

1 - Remove the section on realism it has nothing to do with the mechanic being designed.

2 - Locking mechanics, devices, materials, etc behind cargo/mining/science has been a long time standing issue in SS13 and has become hard to balance. I definitely want gas miners replaced with a better solution, but needing to rely on cargo or mining for gas adds a dependency to engineering/atmos that doesn't need to exist. And then giving engineers/atmos their own shuttle to go mine the gas themselves creates a separate issue of crew leaving station, which causes more issues in the antag flow.

So I would like to know how would you propose to;

2A - Have more than enough roundstart gas on station to deal with issues
2B - Implementation of a solution that won't cause over-reliance on cargo/mining or requiring frequently leaving the station
2C - Recycling gas instead of just venting it

3 - Pipe Pressure damage shouldn't be just to combat fusion. If it's going to be in there should be a balance of "The current scrubber pipes can deal with the intense heat/cold of a wild station fire" and "these pipes for my burn chamber will need pressure relief and a space loop to work effectively"

If it's to combat fusion, then have canisters, etc melt instead.

3A - If a pipe in the stations main pipenet burst somehow, what tools will the players have to help find the issue?

2023-10-22 00:44 UTC, Partmedia commented
Thank you for your feedback and discussion.

> 1 - Remove the section on realism it has nothing to do with the mechanic being designed.

I'll do that.

> 2 - Locking mechanics, devices, materials, etc behind cargo/mining/science has been a long time standing issue in SS13 and has become hard to balance. I definitely want gas miners replaced with a better solution, but needing to rely on cargo or mining for gas adds a dependency to engineering/atmos that doesn't need to exist. And then giving engineers/atmos their own shuttle to go mine the gas themselves creates a separate issue of crew leaving station, which causes more issues in the antag flow.
> 
> So I would like to know how would you propose to;
> 
> 2A - Have more than enough roundstart gas on station to deal with issues 2B - Implementation of a solution that won't cause over-reliance on cargo/mining or requiring frequently leaving the station 2C - Recycling gas instead of just venting it

I don't currently have a concrete, satisfactory proposal to 2(b). Others have proposed some ideas. Would it be okay if I move the miner removal to "low priority" and add "only if it comes with a better solution to 2(b) that's TBD"?

2(a): definintely

2(c): I PR'd the [gas recycler](https://github.com/space-wizards/space-station-14/pull/9934) a while ago, and this could be used to recycle gas.

> 3A - If a pipe in the stations main pipenet burst somehow, what tools will the players have to help find the issue?

As part of this proposal, I can add "pipe pressure bursting only if a tool like the [new power monitoring console](https://github.com/space-wizards/space-station-14/pull/20927) but for gas pipes"

2023-10-22 00:50 UTC, keronshb commented
> 2(c): I PR'd the [gas recycler](https://github.com/space-wizards/space-station-14/pull/9934) a while ago, and this could be used to recycle gas.

This is really cool! My terminology with this overlapped.

So what I mean was in atmos in SS13, even with miners the station still recycled gas back into the mining chambers.

So for ex if a plasma fire got out and it produced a ton of CO2 but was scrubbed, the scrubbers pump the gas back into their chambers (with the miners) to replenish the gas.

Another solution a friend had was to make the miners cost money. So you can use them to produce more but centcom charges you. Kind of like a gas station that atmos controls (department budget usecase too).

2023-10-22 02:17 UTC, chromiumboy commented
I really like the idea of using the gas recyclers to regenerate O2 and N2 from waste gases. I think waste capture should be an important task for atmos techs. As for replacing lost gas, if we don't want to be overally reliant on cargo, what if these gases were primarily generated from the combustion of plasma? You remove CO2 and N2O from the exhaust fumrs, cool them down, pass then through the gas recyclers, boom, O2 and N2

2023-10-22 02:25 UTC, chromiumboy commented
It also gives you an excuse to have a burn chamber and space radiator system mapped/to be built, even on stations without a TEG. Hell,.on stations with a TEG, you'd be getting power into the bargain

2023-12-11 02:47 UTC, EmoGarbage404 commented
lay claim to your fief, lord.

2023-12-11 02:47 UTC, merged