Update index.md
space-wizards/docs pull request #98
Opened 2023-11-03 01:06 UTC by alwinnocom

Helpful info for new developers.

2023-11-03 01:08 UTC, metalgearsloth requested changes

2023-11-03 01:08 UTC, metalgearsloth commented on src/index.md
> +* [Space Station 14](https://github.com/space-wizards/space-station-14/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) is the main codebase. It has the most priority issues.
This includes your search query.

2023-11-03 01:08 UTC, metalgearsloth commented on src/index.md
> +- [Other](https://github.com/space-wizards)
There's significantly more than this (e.g. RSIEdit, Arch) so better to just say there's others under space-wizards

2023-11-03 01:08 UTC, metalgearsloth commented on src/index.md
> +[🔊 Discord](https://discord.com/invite/rGvu9hKffJ). This is the most active community of developers for Space Station 14. Ask a question on the General or Help channel.
Use the permanent link not this, https://discord.gg/ss14

2024-02-14 13:35 UTC, PJB3005 commented on src/index.md
> +* [Space Station 14](https://github.com/space-wizards/space-station-14) is the main codebase. It has the most priority issues. [Space Station 14 Issues](https://github.com/space-wizards/space-station
Still search query
```suggestion
* [Space Station 14](https://github.com/space-wizards/space-station-14) is the main codebase. It has the most priority issues. [Space Station 14 Issues](https://github.com/space-wizards/space-station-14/issues)
```

2024-02-14 13:36 UTC, merged